backend:
  name: github
  repo: Sulton43/sulton43.github.io
  branch: main
  base_url: https://famous-frangipane-156343.netlify.app//lovely-stardust-6ceead.netlify.app

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog postlar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Sarlavha", name: "title", widget: "string" }
      - { label: "Sana", name: "date", widget: "datetime" }
      - { label: "Kategoriya", name: "category", widget: "select", options: ["Dasturlash", "Kitob", "Hayot", "Umumiy"] }
      - { label: "Matn", name: "body", widget: "markdown" }
